// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'participant_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ParticipantDTO _$ParticipantDTOFromJson(Map<String, dynamic> json) =>
    ParticipantDTO(
      assists: (json['assists'] as num).toInt(),
      baronKills: (json['baronKills'] as num).toInt(),
      bountyLevel: (json['bountyLevel'] as num?)?.toInt(),
      champExperience: (json['champExperience'] as num).toInt(),
      champLevel: (json['champLevel'] as num).toInt(),
      championId: (json['championId'] as num).toInt(),
      championName: json['championName'] as String?,
      championTransform: (json['championTransform'] as num).toInt(),
      consumablesPurchased: (json['consumablesPurchased'] as num).toInt(),
      damageDealtToBuildings: (json['damageDealtToBuildings'] as num).toInt(),
      damageDealtToObjectives: (json['damageDealtToObjectives'] as num).toInt(),
      damageDealtToTurrets: (json['damageDealtToTurrets'] as num).toInt(),
      damageSelfMitigated: (json['damageSelfMitigated'] as num).toInt(),
      deaths: (json['deaths'] as num).toInt(),
      detectorWardsPlaced: (json['detectorWardsPlaced'] as num).toInt(),
      doubleKills: (json['doubleKills'] as num).toInt(),
      dragonKills: (json['dragonKills'] as num).toInt(),
      firstBloodAssist: json['firstBloodAssist'] as bool,
      firstBloodKill: json['firstBloodKill'] as bool,
      firstTowerAssist: json['firstTowerAssist'] as bool,
      firstTowerKill: json['firstTowerKill'] as bool,
      gameEndedInEarlySurrender: json['gameEndedInEarlySurrender'] as bool,
      gameEndedInSurrender: json['gameEndedInSurrender'] as bool,
      goldEarned: (json['goldEarned'] as num).toInt(),
      goldSpent: (json['goldSpent'] as num).toInt(),
      individualPosition: json['individualPosition'] as String?,
      inhibitorKills: (json['inhibitorKills'] as num).toInt(),
      inhibitorTakedowns: (json['inhibitorTakedowns'] as num).toInt(),
      inhibitorsLost: (json['inhibitorsLost'] as num).toInt(),
      item0: (json['item0'] as num).toInt(),
      item1: (json['item1'] as num).toInt(),
      item2: (json['item2'] as num).toInt(),
      item3: (json['item3'] as num).toInt(),
      item4: (json['item4'] as num).toInt(),
      item5: (json['item5'] as num).toInt(),
      item6: (json['item6'] as num).toInt(),
      itemsPurchased: (json['itemsPurchased'] as num).toInt(),
      killingSprees: (json['killingSprees'] as num).toInt(),
      kills: (json['kills'] as num).toInt(),
      lane: json['lane'] as String?,
      largestCriticalStrike: (json['largestCriticalStrike'] as num).toInt(),
      largestKillingSpree: (json['largestKillingSpree'] as num).toInt(),
      largestMultiKill: (json['largestMultiKill'] as num).toInt(),
      longestTimeSpentLiving: (json['longestTimeSpentLiving'] as num).toInt(),
      magicDamageDealt: (json['magicDamageDealt'] as num).toInt(),
      magicDamageDealtToChampions:
          (json['magicDamageDealtToChampions'] as num).toInt(),
      magicDamageTaken: (json['magicDamageTaken'] as num).toInt(),
      neutralMinionsKilled: (json['neutralMinionsKilled'] as num).toInt(),
      nexusKills: (json['nexusKills'] as num).toInt(),
      nexusTakedowns: (json['nexusTakedowns'] as num).toInt(),
      nexusLost: (json['nexusLost'] as num).toInt(),
      objectivesStolen: (json['objectivesStolen'] as num).toInt(),
      objectivesStolenAssists: (json['objectivesStolenAssists'] as num).toInt(),
      participantId: (json['participantId'] as num).toInt(),
      pentaKills: (json['pentaKills'] as num).toInt(),
      perks: PerksDTO.fromJson(json['perks'] as Map<String, dynamic>),
      physicalDamageDealt: (json['physicalDamageDealt'] as num).toInt(),
      physicalDamageDealtToChampions:
          (json['physicalDamageDealtToChampions'] as num).toInt(),
      physicalDamageTaken: (json['physicalDamageTaken'] as num).toInt(),
      profileIcon: (json['profileIcon'] as num).toInt(),
      puuid: json['puuid'] as String?,
      quadraKills: (json['quadraKills'] as num).toInt(),
      riotIdName: json['riotIdName'] as String?,
      riotIdTagline: json['riotIdTagline'] as String?,
      role: json['role'] as String?,
      sightWardsBoughtInGame: (json['sightWardsBoughtInGame'] as num).toInt(),
      spell1Casts: (json['spell1Casts'] as num).toInt(),
      spell2Casts: (json['spell2Casts'] as num).toInt(),
      spell3Casts: (json['spell3Casts'] as num).toInt(),
      spell4Casts: (json['spell4Casts'] as num).toInt(),
      summoner1Casts: (json['summoner1Casts'] as num).toInt(),
      summoner1Id: (json['summoner1Id'] as num).toInt(),
      summoner2Casts: (json['summoner2Casts'] as num).toInt(),
      summoner2Id: (json['summoner2Id'] as num).toInt(),
      summonerId: json['summonerId'] as String?,
      summonerLevel: (json['summonerLevel'] as num).toInt(),
      summonerName: json['summonerName'] as String?,
      teamEarlySurrendered: json['teamEarlySurrendered'] as bool,
      teamId: (json['teamId'] as num).toInt(),
      teamPosition: json['teamPosition'] as String?,
      timeCCingOthers: (json['timeCCingOthers'] as num).toInt(),
      timePlayed: (json['timePlayed'] as num).toInt(),
      totalDamageDealt: (json['totalDamageDealt'] as num).toInt(),
      totalDamageDealtToChampions:
          (json['totalDamageDealtToChampions'] as num).toInt(),
      totalDamageShieldedOnTeammates:
          (json['totalDamageShieldedOnTeammates'] as num).toInt(),
      totalDamageTaken: (json['totalDamageTaken'] as num).toInt(),
      totalHeal: (json['totalHeal'] as num).toInt(),
      totalHealsOnTeammates: (json['totalHealsOnTeammates'] as num).toInt(),
      totalMinionsKilled: (json['totalMinionsKilled'] as num).toInt(),
      totalTimeCCDealt: (json['totalTimeCCDealt'] as num).toInt(),
      totalTimeSpentDead: (json['totalTimeSpentDead'] as num).toInt(),
      totalUnitsHealed: (json['totalUnitsHealed'] as num).toInt(),
      tripleKills: (json['tripleKills'] as num).toInt(),
      trueDamageDealt: (json['trueDamageDealt'] as num).toInt(),
      trueDamageDealtToChampions:
          (json['trueDamageDealtToChampions'] as num).toInt(),
      trueDamageTaken: (json['trueDamageTaken'] as num).toInt(),
      turretKills: (json['turretKills'] as num).toInt(),
      turretTakedowns: (json['turretTakedowns'] as num).toInt(),
      turretsLost: (json['turretsLost'] as num).toInt(),
      unrealKills: (json['unrealKills'] as num).toInt(),
      visionScore: (json['visionScore'] as num).toInt(),
      visionWardsBoughtInGame: (json['visionWardsBoughtInGame'] as num).toInt(),
      wardsKilled: (json['wardsKilled'] as num).toInt(),
      wardsPlaced: (json['wardsPlaced'] as num).toInt(),
      win: json['win'] as bool,
    );
