name: tft_api
description: This package provides an easy way to use the Riot games TFT(Teamfight Tactics) api in Dart language.
version: 0.0.2
repository: https://github.com/Coaspe/riot_api

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.0.2
  riot_api: ^0.0.9
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0