name: lol_api_example
description: Demonstrates how to use the lol_api plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.0
resolution: workspace
dependencies:

  lol_api:
    path: ../
