name: lol_api
description: This package provides an easy way to use the League of Legends api in Dart language.
version: 0.2.0
homepage: https://github.com/Coaspe/riot_api

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  json_annotation: ^4.12.0
  riot_api: ^0.3.0
dev_dependencies:
  build_runner: ^2.15.2
  http: ^1.6.0
  json_serializable: ^6.14.0
  lints: ^6.1.0
  test: ^1.31.2
