name: lol_api
description: League of Legends api.
version: 0.0.4
homepage: https://github.com/Coaspe/riot_api

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.0.2
  riot_api: ^0.0.4
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0