name: Issue
description: Help improve a this repo
body:
  - type: input
    id: Source
    attributes:
      label: Source
      placeholder: "Example: champion_v3.dart"
      validations:
        required: true
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      placeholder: A clear and concise description of what's wrong.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Expected fix
      placeholder: A clear and concise description of how you think we should fix the problem.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      placeholder: Anything else we should know about the problem?
    validations:
      required: false
