name: riot_api
description: This package provides an easy way to use riot api that League of Legends, Valrorant and Legends of Luneterra have in common in Dart language.
version: 0.0.6
homepage: https://github.com/Coaspe/riot_api

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0